import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 * Day3 HomeWork Scoop Selection
 * ScoopListModel
 * @author Student
 */
public class ScoopSelection extends javax.swing.JFrame implements ListSelectionListener {

    
    DefaultListModel flavListModel;
    DefaultListModel selectedListModel;   
    private JList list1;
  
    
    int i = 10;
    
    public ScoopSelection() {
        flavListModel = new DefaultListModel();
        selectedListModel = new DefaultListModel();
        flavListModel.addElement("Venille");
        flavListModel.addElement("Apple");
        flavListModel.addElement("Mango");
        flavListModel.addElement("Peach");
        
        
        JScrollPane listScrollPane = new JScrollPane(listFlav);
        
        list1 = new JList(flavListModel);
        list1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        list1.setSelectedIndex(0);
        list1.addListSelectionListener(this);
        list1.setVisibleRowCount(5);
        
        JButton btAdd = new JButton("Add ->");
        //AddListener addListener = new AddListener(btAdd);
        btAdd.setActionCommand("Add ->");
        //btAdd.addActionListener(addListener);
        btAdd.setEnabled(false);

        btDel = new JButton("Del");
        btDel.setActionCommand("Del");
        //btDel.addActionListener(new DelListener());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFlav = new javax.swing.JList<>();
        btAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btDel = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listSelected = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scoop Flavours Selection");

        jLabel1.setText("Flavours");

        listFlav.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Venille", "Apple", "Peach", "Mango" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listFlav.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listFlav.setToolTipText("");
        listFlav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listFlavMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listFlav);

        btAdd.setText("Add->");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        jLabel2.setText("Selected");

        btDel.setText("Delete Scoop");
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        btClear.setText("Clear All");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(listSelected);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btDel)
                            .addGap(62, 62, 62)
                            .addComponent(btClear))
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDel))
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        int[] index = listFlav.getSelectedIndices();
        String[] flavour = new String[index.length];
        for(int i=0; i<index.length;i++) {
               flavour[i] = flavListModel.get(index[i]).toString();
               //System.out.println("flavour is "+flavour[i]);
               selectedListModel.addElement(flavour[i]);
               listSelected.setModel(selectedListModel);
               selectedListModel.get(i);
               listSelected.getSelectedValue();
            }     
        /*int index2 = listFlav.getSelectedIndex();
        listModel <String> model2 = listFlav.getModel();
        String flavour = model.getElement(index);
        */
        if (flavour.length != 0) {
            listSelected.setSelectedIndex(i);
            listSelected.ensureIndexIsVisible(i);
            //System.out.println("flavour length is not 0");
        } else {
            JOptionPane.showMessageDialog(this,
                    "You forgot to select the flavour",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void listFlavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFlavMouseClicked
        // TODO add your handling code here:
       // JList list = (JList)evt.getSource();
        
    }//GEN-LAST:event_listFlavMouseClicked

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // copy from stackOverflow
        //if(evt.getSource()==btClear) {
        //DefaultListModel selectedListModel = (DefaultListModel) listSelected.getModel();
        selectedListModel.removeAllElements();
    //} 
    }//GEN-LAST:event_btClearActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
        // TODO add your handling code here:
        if (listSelected.getSelectedIndices().length > 0) {
            int[] index = listSelected.getSelectedIndices();
            for(int i=index.length-1; i>=0;i--) {
                selectedListModel.removeElementAt(index[i]);
            }            
        } else {
            JOptionPane.showMessageDialog(this,
                    "You forgot to select the flavour",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btDelActionPerformed

    @Override
    public void valueChanged(ListSelectionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoopSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoopSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoopSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoopSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoopSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listFlav;
    private javax.swing.JList<String> listSelected;
    // End of variables declaration//GEN-END:variables
}
